work_dir: ./work_dir/paper_version/
mesh_path: ./datasets/mixamo/shape/
texture_path: ./datasets/mixamo/texture_datapath/
video_path: ./render_dir/paper_version/

model_save_name: star
device: [0]
seed: 42
description: This is the inference process of STaR, with rendered videos.
wandb_tags: ['STaR']

euler_order: yzx
max_length: 60
num_joints: 22
margin: 0.3

# inference_scanret_feeder: datasets.inference_feeder_scanret.Feeder
# inference_scanret_feeder_args:
#   source_path:
#   q_path: ./datasets/mixamo/test_q_scanret/
#   stats_path: ./datasets/mixamo/stats_scanret/
#   shape_path: ./datasets/mixamo/new_train_shape_uv_scanret/
#   texture_path: ./datasets/mixamo/texture_datapath/
#   min_steps: 60
#   max_steps: 60

inference_feeder: datasets.inference_set.Feeder
inference_feeder_args:
  inference_pairs: ./datasets/mixamo/inference/inference.json
  inference_data_path: ./datasets/mixamo/inference/inference_data.npy  # simple version
  source_path: ./datasets/mixamo/inference/inference_source/
  q_path: ./datasets/mixamo/inference/inference_q/
  stats_path: ./datasets/mixamo/stats/
  shape_path: ./datasets/mixamo/test_shape/  # test shapes are more than train shapes, for unseen characters
  min_steps: 120
  max_steps: 120

model_path: method.network
model_name: Retarget_Model
optimize_param:
  - delta_shape_dec

model_args:
  num_joint: 22
  num_frame: 60
  token_channels: 64
  hidden_channels: 64
  embed_channels: 32

scale_info_path: ./datasets/mixamo/scale_info/
hand_vert_num: 200
limb_vert_num: 300
wo_limb_vert_num: 4000

test_weights: retarget_model.pt
test_ignore_weights: []

encoding_model: Pct
encoding_model_args:
  dropout: 0.5
  output_channels: 40
encoding_model_weights: datasets/mixamo/encoding_model_weights/model.t7

epoch: 50
global_epoch: 50
step: [30]
global_step: [30]
batch_size: 16
test_k: 0.8
test_batch_size: 64
